import os
import json
from datetime import datetime

class BugCrowdSubmitter:
    """
    Submit to BugCrowd (manual assistance only).
    Menghasilkan template laporan dan instruksi manual karena BugCrowd tidak menyediakan API publik.
    
    REALITAS TEKNIS:
    - BugCrowd TIDAK memiliki API publik untuk submit laporan atau upload bukti
    - Hanya bisa submit manual via web interface
    - ARC hanya bisa membantu generate template dan bukti
    """
    
    def __init__(self, session_cookie: str = None):
        # Session cookie tidak digunakan karena tidak ada API
        self.session_cookie = session_cookie
        self.bc_base_url = "https://bugcrowd.com"
    
    def submit_report(self, program_handle: str, report_data: dict, evidence_files: list = None):
        """
        Generate template laporan BugCrowd untuk submit manual.
        """
        try:
            # Bangun template laporan dalam format BugCrowd
            report_template = self._build_bc_report_template(report_data, program_handle)
            
            # Simpan sebagai file lokal
            timestamp = int(datetime.now().timestamp())
            template_file = f"~/.arc/reports/bugcrowd_{program_handle}_{timestamp}.md"
            template_file = os.path.expanduser(template_file)
            os.makedirs(os.path.dirname(template_file), exist_ok=True)
            
            with open(template_file, 'w') as f:
                f.write(report_template)
            
            # Instruksi manual untuk pengguna
            instructions = (
                f"✅ BugCrowd report template ready!\n\n"
                f"📋 **Manual Submission Steps:**\n"
                f"1. Go to: {self.bc_base_url}/{program_handle}\n"
                f"2. Click 'Submit Report'\n"
                f"3. Copy content from: {template_file}\n"
                f"4. Upload evidence files manually:\n"
            )
            
            if evidence_files:
                for i, file_path in enumerate(evidence_files[:5], 1):
                    instructions += f"   {i}. {os.path.basename(file_path)}\n"
            
            return {
                'success': True,
                'template_file': template_file,
                'message': instructions,
                'report_url': f"{self.bc_base_url}/{program_handle}"
            }
        
        except Exception as e:
            return {
                'success': False,
                'error': f'BugCrowd template generation failed: {str(e)}'
            }
    
    def handle_triage_request(self, request_type: str, request_details: dict):
        """
        TIDAK BISA menangani permintaan triage secara otomatis.
        Hanya memberikan instruksi untuk generate bukti manual.
        """
        finding_id = request_details.get('finding_id', 'unknown')
        platform = 'bugcrowd'
        
        return {
            'success': False,
            'message': (
                f"⚠️ BugCrowd doesn't support auto-response to triage requests.\n\n"
                f"📱 **Use Telegram commands to generate evidence:**\n"
                f"/generate_screenshot {platform} {finding_id}\n"
                f"/generate_evidence har {platform} {finding_id}\n"
                f"/generate_patch {platform} {finding_id}\n\n"
                f"📤 Then upload manually to BugCrowd report."
            )
        }
    
    def set_evidence_generator(self, evidence_generator):
        """Set evidence generator untuk integrasi."""
        self.evidence_generator = evidence_generator
    
    def set_patch_generator(self, patch_generator):
        """Set patch generator untuk integrasi."""
        self.patch_generator = patch_generator
    
    def _build_bc_report_template(self, report_data: dict, program_handle: str) -> str:
        """Bangun template laporan dalam format BugCrowd."""
        severity_mapping = {
            'critical': 'Critical',
            'high': 'High', 
            'medium': 'Medium',
            'low': 'Low',
            'info': 'Informational'
        }
        
        template = f"""# Vulnerability Report

## Program
{program_handle}

## Title
{report_data.get('title', f"{report_data.get('vulnerability_type', 'Vulnerability')}")}

## Vulnerability Type
{report_data.get('vulnerability_type', 'Other').title()}

## Severity
{severity_mapping.get(report_data.get('severity', 'medium').lower(), 'Medium')}

## Affected URL
{report_data.get('target_url', 'N/A')}

## Description
{report_data.get('technical_description', 'No description provided')}

## Steps to Reproduce
{report_data.get('reproduction_steps', 'Steps not specified')}

## Impact
{report_data.get('business_impact', 'Significant impact')}

## Remediation
{report_data.get('remediation_advice', 'Implement proper input validation and output encoding.')}

---
*Generated by Mr Esse14 • {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        return template