import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import os
from datetime import datetime

class VDPEmailSender:
    """
    Send VDP reports via email.
    Mengirim laporan VDP melalui email ke program pemerintah.
    """
    
    def __init__(self, smtp_server: str, smtp_port: int, email_user: str, email_password: str):
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        self.email_user = email_user
        self.email_password = email_password
    
    def send_vdp_report(self, recipient_email: str, vdp_data: dict, report_files: list = None):
        """
        Kirim laporan VDP melalui email.
        """
        try:
            # Buat pesan email
            msg = MIMEMultipart()
            msg['From'] = self.email_user
            msg['To'] = recipient_email
            msg['Subject'] = f"Vulnerability Report - {vdp_data.get('agency', 'Unknown Agency')}"
            
            # Buat body email
            body = self._format_vdp_email_body(vdp_data)
            msg.attach(MIMEText(body, 'html'))
            
            # Lampirkan file laporan jika tersedia
            if report_files:
                for file_path in report_files[:5]:  # Batasi 5 lampiran
                    if os.path.exists(file_path):
                        self._attach_file(msg, file_path)
            
            # Kirim email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.email_user, self.email_password)
                server.send_message(msg)
            
            return {
                'success': True,
                'recipient': recipient_email,
                'message': 'VDP report sent successfully via email'
            }
        
        except Exception as e:
            return {
                'success': False,
                'error': f'VDP email sending failed: {str(e)}'
            }
    
    def _format_vdp_email_body(self, vdp_data: dict) -> str:
        """Format body email VDP."""
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6;">
            <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px;">
                <h2 style="color: #007bff;">Vulnerability Disclosure Report</h2>
                
                <h3>Agency Information</h3>
                <p><strong>Agency:</strong> {vdp_data.get('agency', 'N/A')}</p>
                <p><strong>VDP URL:</strong> <a href="{vdp_data.get('vdp_url', '#')}">{vdp_data.get('vdp_url', 'N/A')}</a></p>
                <p><strong>Jurisdiction:</strong> {vdp_data.get('jurisdiction', 'International')}</p>
                
                <h3>Vulnerability Details</h3>
                <p><strong>Type:</strong> {vdp_data.get('vulnerability_type', 'N/A')}</p>
                <p><strong>Affected System:</strong> {vdp_data.get('target_url', 'N/A')}</p>
                <p><strong>Severity:</strong> {vdp_data.get('severity', 'Medium')}</p>
                
                <h3>Technical Description</h3>
                <p>{vdp_data.get('technical_description', 'No description provided')}</p>
                
                <h3>Reproduction Steps</h3>
                <p>{vdp_data.get('reproduction_steps', 'Steps not specified')}</p>
                
                <h3>Business Impact</h3>
                <p>{vdp_data.get('business_impact', 'Impact analysis not provided')}</p>
                
                <hr>
                <p><em>Generated by ARC v7.6 Final • {timestamp}</em></p>
                <p><small>This report is submitted in accordance with your Vulnerability Disclosure Policy.</small></p>
            </div>
        </body>
        </html>
        """
        
        return body
    
    def _attach_file(self, msg: MIMEMultipart, file_path: str):
        """Lampirkan file ke email."""
        with open(file_path, "rb") as attachment:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(attachment.read())
        
        encoders.encode_base64(part)
        part.add_header(
            'Content-Disposition',
            f'attachment; filename= {os.path.basename(file_path)}'
        )
        msg.attach(part)