import os
import json
from datetime import datetime

class YesWeHackSubmitter:
    """
    Submit to YesWeHack (manual assistance only).
    Menghasilkan template laporan dan instruksi manual karena YesWeHack tidak menyediakan API publik.
    
    REALITAS TEKNIS:
    - YesWeHack TIDAK memiliki API publik
    - Hanya bisa submit manual via web interface  
    - ARC hanya bisa membantu generate template dan bukti
    """
    
    def __init__(self, session_cookie: str = None):
        self.session_cookie = session_cookie
        self.ywh_base_url = "https://yeswehack.com"
    
    def submit_report(self, program_handle: str, report_data: dict, evidence_files: list = None):
        """
        Generate template laporan YesWeHack untuk submit manual.
        """
        try:
            report_template = self._build_ywh_report_template(report_data, program_handle)
            
            timestamp = int(datetime.now().timestamp())
            template_file = f"~/.arc/reports/yeswehack_{program_handle}_{timestamp}.md"
            template_file = os.path.expanduser(template_file)
            os.makedirs(os.path.dirname(template_file), exist_ok=True)
            
            with open(template_file, 'w') as f:
                f.write(report_template)
            
            instructions = (
                f"✅ YesWeHack report template ready!\n\n"
                f"📋 **Manual Submission Steps:**\n"
                f"1. Login to YesWeHack\n"
                f"2. Navigate to program: {program_handle}\n"
                f"3. Click 'Submit Report'\n"
                f"4. Fill form using content from: {template_file}\n"
                f"5. Upload evidence files manually\n"
            )
            
            return {
                'success': True,
                'template_file': template_file,
                'message': instructions,
                'report_url': f"{self.ywh_base_url}/programs/{program_handle}"
            }
        
        except Exception as e:
            return {
                'success': False,
                'error': f'YesWeHack template generation failed: {str(e)}'
            }
    
    def handle_triage_request(self, request_type: str, request_details: dict):
        """
        TIDAK BISA menangani permintaan triage secara otomatis.
        """
        finding_id = request_details.get('finding_id', 'unknown')
        platform = 'yeswehack'
        
        return {
            'success': False,
            'message': (
                f"⚠️ YesWeHack doesn't support auto-response to triage requests.\n\n"
                f"📱 **Use Telegram commands to generate evidence:**\n"
                f"/generate_screenshot {platform} {finding_id}\n"
                f"/generate_evidence pcap {platform} {finding_id}\n"
                f"/generate_patch {platform} {finding_id}\n\n"
                f"📤 Then upload manually to YesWeHack report."
            )
        }
    
    def set_evidence_generator(self, evidence_generator):
        """Set evidence generator untuk integrasi."""
        self.evidence_generator = evidence_generator
    
    def set_patch_generator(self, patch_generator):
        """Set patch generator untuk integrasi."""
        self.patch_generator = patch_generator
    
    def _build_ywh_report_template(self, report_data: dict, program_handle: str) -> str:
        """Bangun template laporan dalam format YesWeHack."""
        template = f"""# Security Vulnerability Report

## Program Information
- **Program**: {program_handle}
- **Target**: {report_data.get('target_url', 'N/A')}
- **Vulnerability Type**: {report_data.get('vulnerability_type', 'Other').title()}
- **Severity**: {report_data.get('severity', 'Medium').title()}

## Technical Details

### Description
{report_data.get('technical_description', 'No description provided')}

### Proof of Concept
{report_data.get('poc_description', 'Provide step-by-step reproduction with screenshots')}

### Impact Analysis
{report_data.get('business_impact', 'Describe potential business impact')}

### Affected Components
- URL: {report_data.get('target_url', 'N/A')}
- Parameters: {report_data.get('affected_parameters', 'N/A')}
- HTTP Method: {report_data.get('http_method', 'GET/POST')}

## Remediation Recommendations
{report_data.get('remediation_advice', 'Provide specific code examples and best practices')}

## Additional Information
- **Researcher**: Mr Esse14
- **Discovery Date**: {datetime.now().strftime('%Y-%m-%d')}
- **Report Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---
*This report was automatically generated by ARC v7.6 Final*
"""
        return template