import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import requests
import os

class HumanApprovalNotifier:
    """
    Notify you for approval before auto-use.
    Memberitahu Anda untuk persetujuan sebelum penggunaan otomatis.
    """
    
    def __init__(self, notification_config: dict):
        self.config = notification_config
        self.notification_methods = {
            'email': self._send_email_notification,
            'telegram': self._send_telegram_notification,
            'cli': self._send_cli_notification
        }
    
    def request_human_approval(self, tool_info: dict, integration_plan: dict):
        """
        Minta persetujuan manusia sebelum integrasi otomatis.
        """
        results = {
            'tool_info': tool_info,
            'integration_plan': integration_plan,
            'notifications_sent': [],
            'approval_required': True,
            'success': False
        }
        
        try:
            # Bangun pesan notifikasi
            notification_message = self._build_approval_message(tool_info, integration_plan)
            
            # Kirim notifikasi ke semua metode yang dikonfigurasi
            for method in self.config.get('methods', ['cli']):
                if method in self.notification_methods:
                    notify_result = self.notification_methods[method](notification_message)
                    results['notifications_sent'].append({
                        'method': method,
                        'success': notify_result['success'],
                        'error': notify_result.get('error')
                    })
            
            results['success'] = len(results['notifications_sent']) > 0
            results['approval_token'] = self._generate_approval_token(tool_info)
        
        except Exception as e:
            results['error'] = f'Human approval notification failed: {str(e)}'
        
        return results
    
    def _build_approval_message(self, tool_info: dict, integration_plan: dict) -> str:
        """Bangun pesan permintaan persetujuan."""
        message = f"""
AUTO-INTEGRATION REQUEST

A new tool has been discovered and requires your approval:

Tool Name: {tool_info.get('name', 'Unknown')}
Source: {tool_info.get('source', 'Unknown')}
Description: {tool_info.get('description', 'No description')}

Integration Plan:
- Installation Method: {integration_plan.get('method', 'Unknown')}
- Dependencies: {', '.join(integration_plan.get('dependencies', []))}
- Security Impact: {integration_plan.get('security_impact', 'Low')}

Please review and approve this integration.
Approval Token: {self._generate_approval_token(tool_info)}

Generated by ARC v7.6 Final Autonomous Red Cell System
        """
        return message.strip()
    
    def _generate_approval_token(self, tool_info: dict) -> str:
        """Hasilkan token persetujuan unik."""
        import hashlib
        import time
        token_input = f"{tool_info.get('name', '')}_{tool_info.get('source', '')}_{time.time()}"
        return hashlib.sha256(token_input.encode()).hexdigest()[:16]
    
    def _send_email_notification(self, message: str) -> dict:
        """Kirim notifikasi email."""
        try:
            smtp_config = self.config.get('email', {})
            msg = MIMEMultipart()
            msg['From'] = smtp_config.get('from')
            msg['To'] = smtp_config.get('to')
            msg['Subject'] = 'ARC: Auto-Integration Approval Required'
            msg.attach(MIMEText(message, 'plain'))
            
            with smtplib.SMTP(smtp_config.get('server'), smtp_config.get('port', 587)) as server:
                server.starttls()
                server.login(smtp_config.get('username'), smtp_config.get('password'))
                server.send_message(msg)
            
            return {'success': True}
        except Exception as e:
            return {'success': False, 'error': str(e)}
    
    def _send_telegram_notification(self, message: str) -> dict:
        """Kirim notifikasi Telegram."""
        try:
            telegram_config = self.config.get('telegram', {})
            url = f"https://api.telegram.org/bot{telegram_config.get('bot_token')}/sendMessage"
            payload = {
                'chat_id': telegram_config.get('chat_id'),
                'text': message,
                'parse_mode': 'HTML'
            }
            response = requests.post(url, json=payload, timeout=10)
            return {'success': response.status_code == 200}
        except Exception as e:
            return {'success': False, 'error': str(e)}
    
    def _send_cli_notification(self, message: str) -> dict:
        """Kirim notifikasi CLI."""
        try:
            print("\n" + "="*60)
            print("ARC AUTO-INTEGRATION APPROVAL REQUIRED")
            print("="*60)
            print(message)
            print("="*60)
            return {'success': True}
        except Exception as e:
            return {'success': False, 'error': str(e)}