import os
from datetime import datetime

class MultiDocumentGenerator:
    """
    4-doc elite package (technical, exec, legal, CSIRT).
    Menghasilkan paket pelaporan 4 dokumen tingkat elite.
    """
    
    def __init__(self, output_dir="~/.arc/reports"):
        self.output_dir = os.path.expanduser(output_dir)
        os.makedirs(self.output_dir, exist_ok=True)
    
    def generate_four_document_package(self, vulnerability_data: dict, 
                                     evidence_artifacts: dict, report_id: str = None):
        """
        Hasilkan paket 4 dokumen untuk kerentanan.
        """
        if report_id is None:
            report_id = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        report_dir = os.path.join(self.output_dir, report_id)
        os.makedirs(report_dir, exist_ok=True)
        
        documents = {}
        
        try:
            # Technical Report
            tech_doc = self._generate_technical_report(report_dir, vulnerability_data, evidence_artifacts)
            documents['technical'] = tech_doc
            
            # Executive Summary
            exec_doc = self._generate_executive_summary(report_dir, vulnerability_data)
            documents['executive'] = exec_doc
            
            # Legal & Compliance Report
            legal_doc = self._generate_legal_report(report_dir, vulnerability_data)
            documents['legal'] = legal_doc
            
            # CSIRT Action Plan
            csirt_doc = self._generate_csirt_plan(report_dir, vulnerability_data)
            documents['csirt'] = csirt_doc
            
            return {
                'report_id': report_id,
                'report_dir': report_dir,
                'documents': documents,
                'generation_successful': True
            }
        
        except Exception as e:
            return {
                'report_id': report_id,
                'error': f'Four-document package generation failed: {str(e)}',
                'generation_successful': False
            }
    
    def _generate_technical_report(self, report_dir: str, vuln_data: dict, evidence: dict) -> str:
        """Hasilkan laporan teknis."""
        vuln_type = vuln_data.get('type', 'unknown').upper()
        target_url = vuln_data.get('target_url', 'N/A')
        severity = vuln_data.get('severity', 'Medium')
        technical_details = vuln_data.get('technical_details', 'No details provided')
        reproduction_steps = vuln_data.get('reproduction_steps', 'Steps not specified')
        
        content = f"""# Technical Vulnerability Report

## Vulnerability Details
- **Type**: {vuln_type}
- **Target**: {target_url}
- **Severity**: {severity}
- **CVSS Score**: {vuln_data.get('cvss_score', 'N/A')}

## Technical Description
{technical_details}

## Reproduction Steps
{reproduction_steps}

## Evidence Artifacts
- Video PoC: {evidence.get('video_path', 'Not available')}
- HAR File: {evidence.get('har_path', 'Not available')}
- Reproduction Script: {evidence.get('payload_script', 'Not available')}

## Impact Analysis
{vuln_data.get('business_impact', 'Impact analysis not provided')}

## Generated By
ARC v7.6 Final Autonomous Red Cell System
Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
        
        file_path = os.path.join(report_dir, '01_technical_report.md')
        with open(file_path, 'w') as f:
            f.write(content)
        return file_path
    
    def _generate_executive_summary(self, report_dir: str, vuln_data: dict) -> str:
        """Hasilkan ringkasan eksekutif."""
        vuln_type = vuln_data.get('type', 'unknown').title()
        target_url = vuln_data.get('target_url', 'N/A')
        severity = vuln_data.get('severity', 'Medium')
        business_impact = vuln_data.get('business_impact', 'Significant business impact')
        estimated_bounty = vuln_data.get('estimated_bounty_usd', 'N/A')
        
        content = f"""# Executive Summary

## Critical Security Finding

A **{severity}** security vulnerability has been identified in your system:

- **Vulnerability**: {vuln_type}
- **Affected System**: {target_url}
- **Business Impact**: {business_impact}
- **Estimated Bounty**: ${estimated_bounty:,} USD

## Key Recommendations
1. **Immediate Triage**: Assign to security team within 24 hours
2. **Validation**: Verify using provided reproduction artifacts
3. **Remediation**: Apply patches within 72 hours for critical findings
4. **Communication**: Coordinate disclosure timeline with researcher

## Risk Assessment
This finding represents a **{severity}** risk to your organization's:
- Data confidentiality and integrity
- Customer trust and reputation  
- Regulatory compliance status
- Financial stability

## Next Steps
Please acknowledge receipt of this report and provide an estimated timeline for remediation.

---
*Generated by ARC v7.6 Final - Professional Security Research*
"""
        
        file_path = os.path.join(report_dir, '02_executive_summary.md')
        with open(file_path, 'w') as f:
            f.write(content)
        return file_path
    
    def _generate_legal_report(self, report_dir: str, vuln_data: dict) -> str:
        """Hasilkan laporan legal & compliance."""
        jurisdiction = vuln_data.get('jurisdiction', 'international')
        regulatory_framework = vuln_data.get('regulatory_framework', 'ISO/IEC 30111')
        legal_requirements = vuln_data.get('legal_requirements', {})
        
        content = f"""# Legal & Compliance Report

## Regulatory Context
- **Jurisdiction**: {jurisdiction.title()}
- **Applicable Framework**: {regulatory_framework}
- **Disclosure Requirements**: {legal_requirements.get('disclosure_window', 'Reasonable timeframe')}

## Legal Obligations
"""
        
        if legal_requirements.get('required_info'):
            content += "\n### Required Information\n"
            for req in legal_requirements['required_info']:
                content += f"- {req}\n"
        
        if jurisdiction == 'indonesia':
            content += f"""
## Indonesian Regulatory Pressure
This vulnerability falls under **UU PDP No. 27/2022** and **POJK No. 13/2023**, which mandates:

- Pelaporan insiden dalam **72 jam** sejak penemuan
- Notifikasi kepada pemilik data yang terdampak
- Audit forensik wajib untuk insiden kritis

**Konsekuensi**: Denda hingga 2% dari pendapatan tahunan atau Rp5 miliar.
"""
        elif jurisdiction == 'eu':
            content += f"""
## GDPR Compliance Pressure
Under **GDPR Article 33**, you must:

- Report to supervisory authority within **72 hours**
- Document the nature, scope, and impact of the breach
- Implement appropriate technical and organizational measures

**Consequences**: Fines up to €20 million or 4% of global annual turnover.
"""
        
        content += f"""
## Recommended Legal Actions
1. Consult with legal counsel immediately
2. Initiate incident response procedures per regulatory requirements
3. Prepare regulatory filings if required
4. Document all remediation efforts for compliance purposes

---
*Generated by ARC v7.6 Final - Regulatory-Aware Security Research*
"""
        
        file_path = os.path.join(report_dir, '03_legal_compliance.md')
        with open(file_path, 'w') as f:
            f.write(content)
        return file_path
    
    def _generate_csirt_plan(self, report_dir: str, vuln_data: dict) -> str:
        """Hasilkan rencana tindakan CSIRT."""
        vuln_type = vuln_data.get('type', 'unknown')
        target_url = vuln_data.get('target_url', 'N/A')
        severity = vuln_data.get('severity', 'Medium')
        
        content = f"""# CSIRT Action Plan

## Incident Classification
- **Vulnerability Type**: {vuln_type.upper()}
- **Affected Asset**: {target_url}
- **Severity Level**: {severity.upper()}
- **Priority**: {'HIGH' if severity in ['critical', 'high'] else 'MEDIUM'}

## Immediate Actions (Within 24 Hours)
1. **Triage & Validation**
   - [ ] Reproduce vulnerability using provided artifacts
   - [ ] Assess actual impact on production systems
   - [ ] Determine affected user/data scope

2. **Containment**
   - [ ] Implement temporary WAF rules if applicable
   - [ ] Restrict access to vulnerable endpoints
   - [ ] Monitor for active exploitation attempts

3. **Communication**
   - [ ] Acknowledge report to researcher
   - [ ] Notify internal stakeholders
   - [ ] Prepare initial incident response documentation

## Short-term Remediation (Within 72 Hours)
1. **Patch Development**
   - [ ] Apply recommended code fixes from patch factory
   - [ ] Test patches in staging environment
   - [ ] Validate fix effectiveness

2. **Deployment**
   - [ ] Deploy patches to production
   - [ ] Verify vulnerability is resolved
   - [ ] Update security documentation

## Long-term Prevention
1. **Process Improvements**
   - [ ] Add vulnerability type to security testing checklist
   - [ ] Implement automated detection for similar issues
   - [ ] Conduct security training for development team

2. **Monitoring**
   - [ ] Add detection rules to SIEM/SOC
   - [ ] Implement continuous vulnerability scanning
   - [ ] Review and update WAF policies

## Success Criteria
- [ ] Vulnerability confirmed resolved
- [ ] No active exploitation detected
- [ ] Researcher satisfied with resolution
- [ ] Regulatory requirements met (if applicable)

---
*Generated by ARC v7.6 Final - CSIRT-Ready Security Research*
"""
        
        file_path = os.path.join(report_dir, '04_csirt_action_plan.md')
        with open(file_path, 'w') as f:
            f.write(content)
        return file_path