import os
import sys
from datetime import datetime


class ReproducibilityBuilder:
    """
    payload.py + README.md (engineer-ready reproduction).
    Membangun paket reproduksi siap pakai untuk engineer CSIRT.
    """

    def __init__(self, output_dir="~/.arc/evidence"):
        self.output_dir = os.path.expanduser(output_dir)
        os.makedirs(self.output_dir, exist_ok=True)

    def build_reproducibility_package(self, vulnerability_data: dict,
                                     exploit_payload: str, report_id: str = None):
        """
        Bangun paket reproduksi untuk kerentanan.
        """
        if report_id is None:
            report_id = f"repro_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

        package_dir = os.path.join(self.output_dir, report_id)
        os.makedirs(package_dir, exist_ok=True)

        try:
            # Generate payload script
            payload_path = self._generate_payload_script(package_dir, exploit_payload, vulnerability_data)

            # Generate README
            readme_path = self._generate_readme(package_dir, vulnerability_data, payload_path)

            return {
                'report_id': report_id,
                'package_dir': package_dir,
                'payload_script': payload_path,
                'readme_file': readme_path,
                'build_successful': True
            }

        except Exception as e:
            return {
                'report_id': report_id,
                'error': f'Reproducibility package build failed: {str(e)}',
                'build_successful': False
            }

    def _generate_payload_script(self, package_dir: str, payload: str, vuln_data: dict) -> str:
        """Hasilkan skrip payload."""
        vuln_type = vuln_data.get('type', 'unknown')
        target_url = vuln_data.get('target_url', '')
        parameter_name = vuln_data.get('parameter', 'vuln_param')
        method = vuln_data.get('method', 'POST')

        # Escape triple quotes in payload to prevent syntax errors
        escaped_payload = payload.replace('"""', '\\"\\"\\"')

        script_content = f'''#!/usr/bin/env python3
"""
Reproduction Script for {vuln_type.upper()} Vulnerability
Target: {target_url}
Generated by ARC v7.6 Final Autonomous Red Cell System
"""

import requests
import sys


def reproduce_vulnerability():
    """Reproduce the vulnerability."""
    target = "{target_url}"
    payload = """{escaped_payload}"""
    parameter = "{parameter_name}"
    method = "{method}"

    print(f"[+] Target: {{target}}")
    print(f"[+] Payload: {{payload[:50]}}..." if len(payload) > 50 else f"[+]: {{payload}}")

    try:
        # Execute the exploit with proper method handling
        if method.upper() == "GET":
            params = {{parameter: payload}}
            response = requests.get(target, params=params, timeout=10)
        else:
            data = {{parameter: payload}}
            response = requests.post(target, data=data, timeout=10)

        print(f"[+] Status Code: {{response.status_code}}")
        print(f"[+] Response Length: {{len(response.content)}}")

        # Check for successful exploitation (customize based on vulnerability type)
        success_indicators = {{
            'xss': ['<script>', 'onerror=', 'alert('],
            'sqli': ['sql syntax', 'mysql_fetch', 'database error'],
            'ssrf': ['127.0.0.1', 'localhost', 'internal'],
            'rce': ['root:', 'www-data', '/bin/'],
            'lfi': ['root:x:0:0', '[extensions]']
        }}

        vuln_category = '{vuln_type}'.lower()
        indicators = success_indicators.get(vuln_category, ['vulnerable_pattern'])

        if any(indicator in response.text.lower() for indicator in indicators):
            print("[+] EXPLOIT SUCCESSFUL!")
            return True
        else:
            print("[-] Exploit may have failed - check manually")
            return False

    except requests.exceptions.Timeout:
        print("[-] Request timed out - target may be slow or protected")
        return False
    except requests.exceptions.ConnectionError:
        print("[-] Connection error - check target URL and network")
        return False
    except Exception as e:
        print(f"[-] Error: {{e}}")
        return False


if __name__ == "__main__":
    success = reproduce_vulnerability()
    sys.exit(0 if success else 1)
'''

        script_path = os.path.join(package_dir, 'payload.py')
        with open(script_path, 'w') as f:
            f.write(script_content)

        # Make executable (handle Windows compatibility)
        try:
            os.chmod(script_path, 0o755)
        except (OSError, AttributeError):
            # Skip chmod on Windows
            pass

        return script_path

    def _generate_readme(self, package_dir: str, vuln_data: dict, payload_path: str) -> str:
        """Hasilkan file README."""
        vuln_type = vuln_data.get('type', 'unknown').upper()
        target_url = vuln_data.get('target_url', 'N/A')
        severity = vuln_data.get('severity', 'Medium')
        description = vuln_data.get('description', 'No description provided')
        parameter = vuln_data.get('parameter', 'vuln_param')
        method = vuln_data.get('method', 'POST')

        readme_content = f"""# Vulnerability Reproduction Package

## Overview
- **Vulnerability Type**: {vuln_type}
- **Target**: {target_url}
- **Parameter**: `{parameter}`
- **HTTP Method**: {method}
- **Severity**: {severity}
- **Description**: {description}

## Files
- `payload.py`: Python script to reproduce the vulnerability
- This README: Usage instructions and context

## Usage
1. Ensure you have Python 3 and requests library installed:
   ```bash
   pip install requests
   ```

2. Run the reproduction script:
   ```bash
   python3 payload.py
   ```

3. The script will output the HTTP status code and response length.
   If exploitation is successful, you should see "EXPLOIT SUCCESSFUL!".

## Ethical Notice
This package is provided for authorized security testing only.
Ensure you have explicit written permission before testing on any system.

## Generated By
ARC v7.6 Final Autonomous Red Cell System
Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""

        readme_path = os.path.join(package_dir, 'README.md')
        with open(readme_path, 'w') as f:
            f.write(readme_content)

        return readme_path