import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

class EmailNotifier:
    """
    Email notifications for VDP.
    Mengirim notifikasi email untuk program VDP.
    """
    
    def __init__(self, smtp_server: str = None, smtp_port: int = None, 
                 email_user: str = None, email_password: str = None):
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        self.email_user = email_user
        self.email_password = email_password
    
    def send_vdp_notification(self, recipient_email: str, vdp_data: dict):
        """
        Kirim notifikasi VDP melalui email.
        """
        if not all([self.smtp_server, self.smtp_port, self.email_user, self.email_password]):
            return {'error': 'Email configuration incomplete'}
        
        try:
            # Buat pesan email
            msg = MIMEMultipart()
            msg['From'] = self.email_user
            msg['To'] = recipient_email
            msg['Subject'] = f"🚨 VDP Alert: {vdp_data.get('agency', 'Unknown Agency')}"
            
            # Buat body email
            body = self._format_vdp_email_body(vdp_data)
            msg.attach(MIMEText(body, 'html'))
            
            # Kirim email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.email_user, self.email_password)
                server.send_message(msg)
            
            return {'success': True, 'recipient': recipient_email}
        
        except Exception as e:
            return {'error': f'Email notification failed: {str(e)}'}
    
    def _format_vdp_email_body(self, vdp_data: dict) -> str:
        """Format body email VDP."""
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6;">
            <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px;">
                <h2 style="color: #dc3545;">🚨 Vulnerability Disclosure Program Alert</h2>
                
                <p><strong>Agency:</strong> {vdp_data.get('agency', 'N/A')}</p>
                <p><strong>VDP URL:</strong> <a href="{vdp_data.get('vdp_url', '#')}">{vdp_data.get('vdp_url', 'N/A')}</a></p>
                <p><strong>Jurisdiction:</strong> {vdp_data.get('jurisdiction', 'International')}</p>
                <p><strong>Framework:</strong> {vdp_data.get('framework', 'ISO/IEC 30111')}</p>
                
                <h3>📋 Requirements:</h3>
                <ul>
        """
        
        requirements = vdp_data.get('requirements', {})
        for req_type, details in requirements.items():
            body += f"<li><strong>{req_type.title()}:</strong> {details}</li>"
        
        body += f"""
                </ul>
                
                <hr>
                <p><em>Generated by ARC v7.6 Final • {timestamp}</em></p>
                <p><small>This is an automated notification from your Autonomous Red Cell system.</small></p>
            </div>
        </body>
        </html>
        """
        
        return body